// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package handler

import (
	"github.com/skygeario/skygear-server/pkg/core/config"
	"net/http"
)

// Injectors from wire.go:

func InjectRootHandler(r *http.Request) *RootHandler {
	rootHandler := NewRootHandler()
	return rootHandler
}

// wire.go:

func ProvideTenantConfig(r *http.Request) *config.TenantConfiguration {
	return config.GetTenantConfig(r.Context())
}
